There is a Huge Update about image detect game win rate  fix bug and reduce delay every card has minimum 30 photo for ai detect
matthewmiglio/py-clash-bot pull request #207
Opened 2023-04-01 07:20 UTC by hasanalt

2023-04-02 15:51 UTC, marmig0404 requested changes
could you drop the `.pyc` files and force push?
let me know if you need help doing that, i can find you some resources.

could you also edit the PR description to explain the exact changes and why they were made? I understand adding more images for detection, but why are there changes in the timing and click coordinates?

2023-04-02 16:10 UTC, hasanalt commented
> could you drop the `.pyc` files and force push? let me know if you need help doing that, i can find you some resources.
> 
> could you also edit the PR description to explain the exact changes and why they were made? I understand adding more images for detection, but why are there changes in the timing and click coordinates?
Look Like I Falsely Edit .pyc file XD 
Here İs All Change About This
Every Character has minimum 30 image
reduced some time.sleep in navigation.py
i found an issue when fireball shoot its shoot main tower too its fixed
and improved card drop location

2023-04-02 21:03 UTC, matthewmiglio commented
Can you explain what's going on with the coordinate changes in the get_play_coords() method in card_detection.py

2023-04-03 18:23 UTC, marmig0404 approved these changes

2023-04-03 22:17 UTC, merged